import 'package:flutter/material.dart';
import 'package:food_analyzer_app/core/theme/category_accent_colors.dart';

class ProductCategory {
  final String id;
  final String title;
  final IconData icon;
  final String? imageAsset;
  final List<String> positiveKeywords;
  final List<String> requiredAnyKeywords;
  final List<String> negativeKeywords;
  final List<String> offCategoryTags;
  final List<String> excludedOffCategoryTags;
  final List<String> synonyms;
  final List<String> offFallbackQueries;
  final String description;
  final List<String> databaseTags;
  final Color color;

  List<String> get keywords =>
      <String>{...positiveKeywords, ...synonyms}.toList(growable: false);

  const ProductCategory({
    required this.id,
    required this.title,
    required this.icon,
    required this.positiveKeywords,
    this.imageAsset,
    this.requiredAnyKeywords = const [],
    this.negativeKeywords = const [],
    this.offCategoryTags = const [],
    this.excludedOffCategoryTags = const [],
    this.synonyms = const [],
    this.offFallbackQueries = const [],
    this.description = '',
    this.databaseTags = const [],
    required this.color,
  });
}

/// FreshScan's 12-category taxonomy for Turkish packaged food.
///
/// Stable internal IDs match the CanonicalCategoryMapper constants.
/// There are no shortcut sub-categories in this list; all entries are
/// genuine main categories.
class ProductCategories {
  ProductCategories._();

  static const all = <ProductCategory>[
    ProductCategory(
      id: 'atistirmalik',
      title: 'Atıştırmalık',
      icon: Icons.local_dining,
      imageAsset: 'assets/images/categories/atistirmalik.png',
      positiveKeywords: [
        'atıştırmalık',
        'atistirmalik',
        'snack',
        'aperatif',
        'kuruyemiş',
        'kuruyemis',
        'bisküvi',
        'biskuvi',
        'cips',
        'çikolata',
        'cikolata',
        'kraker',
        'gofret',
      ],
      negativeKeywords: [
        'salam',
        'sucuk',
        'sosis',
        'ketçap',
        'ketcap',
        'mayonez',
        'süt',
        'sut',
        'yoğurt',
        'yogurt',
        'peynir',
        'ton balığı',
        'ton baligi',
        'tuna',
      ],
      synonyms: ['chips', 'cracker', 'wafer', 'cookie'],
      offCategoryTags: [
        'en:snacks',
        'en:salty-snacks',
        'en:chocolates',
        'en:biscuits',
        'en:cakes',
        'en:cookies',
        'en:chips-and-fries',
        'en:crisps',
        'en:crackers',
      ],
      excludedOffCategoryTags: [
        'en:prepared-meats',
        'en:sauces',
        'en:fish-products',
      ],
      databaseTags: [
        'atistirmalik',
        'biskuvi_kek',
        'cips_kraker',
        'cikolata_gofret',
        'saglikli_protein',
        'biskuvi',
        'cips',
        'kuruyemis',
        'cikolata',
        'bar_kaplamalilar',
        'kek',
        'kraker',
        'sekerleme',
        'misir_pirinc_patlagi',
        'kuru_meyve',
        'sakiz',
      ],
      offFallbackQueries: [
        'atıştırmalık',
        'kuruyemiş',
        'bisküvi',
        'çikolata',
        'kraker',
      ],
      color: CategoryAccentColors.atistirmalik,
    ),

    ProductCategory(
      id: 'icecek',
      title: 'İçecek',
      icon: Icons.local_drink,
      imageAsset: 'assets/images/categories/icecek.png',
      positiveKeywords: [
        'içecek',
        'icecek',
        'drink',
        'beverage',
        'meyve suyu',
        'limonata',
        'kola',
        'cola',
        'soda',
        'maden suyu',
        'çay',
        'cay',
        'kahve',
        'coffee',
        'enerji içeceği',
      ],
      synonyms: ['juice', 'energy drink', 'gazoz', 'ayran'],
      offCategoryTags: ['en:beverages', 'en:energy-drinks'],
      databaseTags: [
        'icecekler',
        'enerji_icecekleri',
        'gazli_icecek',
        'gazsiz_icecek',
        'cay',
        'maden_suyu',
        'meyve_suyu',
        'kahve',
      ],
      offFallbackQueries: ['içecek', 'meyve suyu', 'kola', 'enerji içeceği'],
      color: CategoryAccentColors.icecek,
    ),

    ProductCategory(
      id: 'sut-kahvaltilik',
      title: 'Süt & Kahvaltılık',
      icon: Icons.free_breakfast,
      imageAsset: 'assets/images/categories/sut_kahvaltilik.png',
      positiveKeywords: [
        'süt',
        'sut',
        'milk',
        'ayran',
        'kefir',
        'sütlü',
        'sutlu',
        'peynir',
        'cheese',
        'yoğurt',
        'yogurt',
        'labne',
        'kahvaltı',
        'kahvalti',
        'breakfast',
        'reçel',
        'recel',
        'bal',
        'honey',
        'tahin',
        'zeytin',
        'mısır gevreği',
        'misir gevregi',
        'müsli',
        'musli',
        'fındık ezmesi',
        'findik ezmesi',
      ],
      offCategoryTags: [
        'en:dairies',
        'en:milks',
        'en:cheeses',
        'en:yogurts',
        'en:spreads',
        'en:breakfasts',
      ],
      databaseTags: [
        'sut_urunleri',
        'peynir_yogurt',
        'sut',
        'yogurt',
        'peynir',
        'sutlu_tatli_krema',
        'kahvaltilik',
        'findik_ezmesi',
        'kahvaltiliklar',
        'zeytin',
      ],
      offFallbackQueries: [
        'süt',
        'peynir',
        'yoğurt',
        'kahvaltılık',
        'bal reçel',
      ],
      color: CategoryAccentColors.sutKahvaltilik,
    ),

    ProductCategory(
      id: 'temel-gida',
      title: 'Temel Gıda',
      icon: Icons.grain,
      imageAsset: 'assets/images/categories/temel_gida.png',
      positiveKeywords: [
        'makarna',
        'pasta',
        'spaghetti',
        'bulgur',
        'pirinç',
        'pirinc',
        'nohut',
        'mercimek',
        'fasulye',
        'bakliyat',
        'ketçap',
        'ketchup',
        'ketcap',
        'mayonez',
        'sos',
        'sauce',
        'salça',
        'salca',
        'konserve',
        'yağ',
        'yag',
        'oil',
        'margarin',
        'un',
        'flour',
      ],
      synonyms: ['rice', 'lentil', 'bean', 'chickpea'],
      offCategoryTags: [
        'en:pastas',
        'en:legumes',
        'en:sauces',
        'en:canned-foods',
      ],
      databaseTags: [
        'makarna_bakliyat',
        'soslar',
        'sos',
        'konserve',
        'makarna',
        'bakliyat',
        'sivi_yag',
        'tuz_baharat_harc',
        'hamur_pasta_malzemeleri',
        'ozel_beslenme_urunleri',
      ],
      offFallbackQueries: [
        'makarna',
        'bakliyat',
        'ketçap',
        'mayonez',
        'konserve',
      ],
      color: CategoryAccentColors.temelGida,
    ),

    ProductCategory(
      id: 'et-tavuk-balik',
      title: 'Et, Tavuk & Balık',
      icon: Icons.set_meal,
      imageAsset: 'assets/images/categories/et_tavuk_balik.png',
      positiveKeywords: [
        'et',
        'meat',
        'şarküteri',
        'sarkuteri',
        'salam',
        'sucuk',
        'sosis',
        'jambon',
        'pastırma',
        'pastirma',
        'hindi',
        'füme',
        'fume',
        'dana',
        'tavuk',
        'chicken',
        'ton balığı',
        'ton baligi',
        'tuna',
        'sardalye',
        'sardine',
        'balık',
        'balik',
        'fish',
      ],
      requiredAnyKeywords: [
        'salam',
        'sucuk',
        'sosis',
        'jambon',
        'pastırma',
        'pastirma',
        'hindi',
        'füme',
        'fume',
        'dana',
        'tavuk',
        'chicken',
        'sausage',
        'salami',
        'ham',
        'meat',
        'şarküteri',
        'sarkuteri',
        'ton balığı',
        'tuna',
        'sardalye',
        'balık',
        'balik',
      ],
      negativeKeywords: [
        'gofret',
        'çikolata',
        'cikolata',
        'bisküvi',
        'biskuvi',
        'biscuit',
        'kek',
        'cake',
        'kraker',
        'cracker',
        'cips',
        'chips',
        'ketçap',
        'ketcap',
        'ketchup',
        'sos',
        'sauce',
        'içecek',
        'icecek',
        'cola',
        'süt',
        'sut',
      ],
      offCategoryTags: [
        'en:meats',
        'en:prepared-meats',
        'en:sausages',
        'en:salami',
        'en:hams',
        'en:poultry',
        'en:turkey',
        'en:chicken',
        'en:beef',
        'en:fish-products',
        'en:tunas',
        'en:canned-fishes',
      ],
      excludedOffCategoryTags: [
        'en:chocolates',
        'en:biscuits',
        'en:cakes',
        'en:crackers',
        'en:sauces',
        'en:beverages',
      ],
      databaseTags: [
        'et_sarkuteri',
        'et-sarkulteri',
        'ton_konserve',
        'sucuk',
        'sosis',
        'salam',
        'jambon',
        'pastirma',
        'fume_et',
        'kavurma',
        'beyaz_et',
        'kirmizi_et',
        'balik_deniz_urunleri',
      ],
      offFallbackQueries: ['salam', 'sucuk', 'sosis', 'ton balığı', 'tavuk'],
      color: CategoryAccentColors.etTavukBalik,
    ),

    ProductCategory(
      id: 'meyve-sebze',
      title: 'Meyve & Sebze',
      icon: Icons.eco,
      imageAsset: 'assets/images/categories/meyve_sebze.png',
      positiveKeywords: [
        'meyve',
        'fruit',
        'sebze',
        'vegetable',
        'salata',
        'salad',
        'yeşillik',
        'domates',
        'tomato',
        'biber',
        'pepper',
      ],
      offCategoryTags: ['en:fruits', 'en:vegetables'],
      databaseTags: [
        'meyve_sebze',
        'meyve',
        'sebze',
        'taze_meyve',
        'taze_sebze',
      ],
      offFallbackQueries: ['meyve', 'sebze', 'salata'],
      color: CategoryAccentColors.meyveSebze,
    ),

    ProductCategory(
      id: 'hazir-donuk',
      title: 'Hazır & Donuk',
      icon: Icons.lunch_dining,
      imageAsset: 'assets/images/categories/hazir_donuk.png',
      positiveKeywords: [
        'hazır yemek',
        'hazir yemek',
        'ready meal',
        'hazır çorba',
        'hazir corba',
        'soup',
        'instant',
        'noodle',
        'ramen',
        'donuk',
        'frozen',
        'meze',
        'pizza',
        'börek',
        'borek',
        'mantı',
        'manti',
      ],
      offCategoryTags: ['en:ready-meals', 'en:frozen-foods'],
      databaseTags: [
        'hazir_yemek',
        'pratik_yemek',
        'meze',
        'hazir_manti',
        'paketli_sandvic',
        'dondurulmus_pizza',
        'dondurulmus_patates',
        'dondurulmus_sebze',
        'dondurulmus_sushi',
        'dondurulmus_meyve',
        'dondurulmus_borek',
        'dondurulmus_manti',
        'pide_lahmacun',
        'dondurulmus_tatli',
        'dondurulmus_firin_urunleri',
        'dondurulmus_hazir_yemek',
      ],
      offFallbackQueries: ['hazır yemek', 'donuk ürün', 'instant noodle'],
      color: CategoryAccentColors.hazirDonuk,
    ),

    ProductCategory(
      id: 'dondurma',
      title: 'Dondurma',
      icon: Icons.ac_unit,
      imageAsset: 'assets/images/categories/dondurma.png',
      positiveKeywords: [
        'dondurma',
        'ice cream',
        'icecream',
        'tatlı',
        'tatli',
        'sweet',
        'dessert',
        'puding',
        'pudding',
      ],
      synonyms: ['magnum', 'cornetto', 'carte dor'],
      offCategoryTags: ['en:ice-creams', 'en:desserts'],
      databaseTags: ['dondurma_tatli', 'kap_dondurma', 'tek_dondurma'],
      offFallbackQueries: ['dondurma', 'tatlı', 'dessert'],
      color: CategoryAccentColors.dondurma,
    ),

    ProductCategory(
      id: 'firin-pastane',
      title: 'Fırın & Pastane',
      icon: Icons.bakery_dining,
      imageAsset: 'assets/images/categories/firin_pastane.png',
      positiveKeywords: [
        'ekmek',
        'bread',
        'unlu mamul',
        'pasta',
        'tart',
        'poğaça',
        'pogaca',
        'çörek',
        'corek',
        'simit',
        'galeta',
        'grissini',
      ],
      offCategoryTags: ['en:breads', 'en:pastries'],
      databaseTags: [
        'firin_pastane',
        'ekmek',
        'unlu_mamul',
        'firin',
        'kuru_pasta',
        'galeta_grissini_gevrek',
        'tatli',
        'pasta',
      ],
      offFallbackQueries: ['ekmek', 'poğaça', 'pasta'],
      color: CategoryAccentColors.firinPastane,
    ),

    ProductCategory(
      id: 'bebek-gida',
      title: 'Bebek Gıda',
      icon: Icons.child_care,
      imageAsset: 'assets/images/categories/bebek_gida.png',
      positiveKeywords: [
        'bebek',
        'baby',
        'çocuk',
        'cocuk',
        'child',
        'mama',
        'ek gıda',
        'ek gida',
        'junior',
        'infant',
      ],
      offCategoryTags: ['en:baby-foods'],
      databaseTags: [
        'bebek_cocuk',
        'bebek_beslenme',
        'bebek_icecegi',
        'bebek_atistirmalik',
      ],
      offFallbackQueries: ['bebek maması', 'baby food', 'çocuk ürünü'],
      color: CategoryAccentColors.bebek,
    ),

    ProductCategory(
      id: 'ozel-beslenme',
      title: 'Özel Beslenme',
      icon: Icons.fitness_center,
      positiveKeywords: [
        'protein',
        'granola',
        'sağlıklı',
        'saglikli',
        'healthy',
        'glutensiz',
        'gluten free',
        'vegan',
        'organik',
        'organic',
        'laktozsuz',
        'lactose free',
        'diyet',
        'diet',
        'light',
        'whey',
        'supplement',
      ],
      offCategoryTags: ['en:protein-bars', 'en:dietary-supplements'],
      databaseTags: [],
      offFallbackQueries: ['protein bar', 'granola', 'glutensiz', 'vegan'],
      color: CategoryAccentColors.ozelBeslenme,
    ),

    ProductCategory(
      id: 'diger',
      title: 'Diğer',
      icon: Icons.category_outlined,
      positiveKeywords: [],
      databaseTags: [],
      color: CategoryAccentColors.diger,
    ),
  ];

  /// Visible categories for public UI (home, tabs, swipe, filter sheets).
  /// Excludes internal fallback categories (Özel Beslenme, Diğer).
  static List<ProductCategory> getVisible() =>
      all.where((c) => c.id != 'ozel-beslenme' && c.id != 'diger').toList();

  static ProductCategory? findById(String id) {
    for (final c in all) {
      if (c.id == id) return c;
    }
    return null;
  }
}
